import { db } from "../firebase.js";
import { collection, addDoc, Timestamp } from "firebase/firestore";

const SEED_REPORTS = [
  // DELHI
  {
    reporterId: "demo_user_1",
    status: "CRITICAL",
    location: { lat: 28.6304, lng: 77.2177, address: "Connaught Place, New Delhi" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "ROAD_DAMAGE", subCategory: "Large Pothole", severity: 9, urgency: "CRITICAL",
      priority: "P1", citizenTitle: "Dangerous pothole near CP Metro", slaHours: 4,
      citizenDescription: "A massive pothole has formed near Connaught Place metro exit causing accidents.",
      department: "Public Works Department (PWD)", estimatedCostInr: 85000,
      publicSafetyThreat: true, preventiveAction: "Avoid the area, use alternate routes",
      riskFactors: ["High traffic", "Near metro exit", "Monsoon damage"], confidence: 0.97,
    },
    routing: { primaryDepartment: "Public Works Department (PWD)", escalationChain: ["PWD Engineer", "Municipal Commissioner"] },
    verificationCount: 12, upvotes: 15, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_2",
    status: "IN_PROGRESS",
    location: { lat: 28.7041, lng: 77.1025, address: "Rohini Sector 9, Delhi" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "WATER_INFRASTRUCTURE", subCategory: "Leaking Water Main", severity: 7, urgency: "HIGH",
      priority: "P2", citizenTitle: "Water main burst in Rohini", slaHours: 24,
      citizenDescription: "A water main has burst on the main road causing waterlogging and water wastage.",
      department: "Jal Board / Water Supply Department", estimatedCostInr: 120000,
      publicSafetyThreat: true, preventiveAction: "Do not drink tap water until fixed",
      riskFactors: ["Water wastage", "Road damage", "Health risk"], confidence: 0.94,
    },
    routing: { primaryDepartment: "Jal Board", escalationChain: ["Chief Engineer Water Supply"] },
    verificationCount: 8, upvotes: 10, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_3",
    status: "RESOLVED",
    location: { lat: 28.5355, lng: 77.391, address: "Noida Sector 18, Delhi NCR" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "ELECTRICAL", subCategory: "Broken Streetlight", severity: 5, urgency: "MEDIUM",
      priority: "P3", citizenTitle: "Street lights out in Sector 18", slaHours: 72,
      citizenDescription: "Multiple streetlights are not working on the main road creating safety issues at night.",
      department: "BSES / State Electricity Board", estimatedCostInr: 35000,
      publicSafetyThreat: false, preventiveAction: "Use torchlight when walking at night",
      riskFactors: ["Night safety", "Crime risk"], confidence: 0.91,
    },
    routing: { primaryDepartment: "BSES Electricity", escalationChain: ["Executive Engineer Electrical"] },
    verificationCount: 5, upvotes: 7, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },

  // MUMBAI
  {
    reporterId: "demo_user_4",
    status: "VERIFIED",
    location: { lat: 19.076, lng: 72.8777, address: "Dadar, Mumbai" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "DRAINAGE", subCategory: "Blocked Drain", severity: 8, urgency: "HIGH",
      priority: "P2", citizenTitle: "Blocked drain causing flooding in Dadar", slaHours: 24,
      citizenDescription: "Storm drain completely blocked causing severe waterlogging during rains.",
      department: "Drainage & Sewerage Department", estimatedCostInr: 65000,
      publicSafetyThreat: true, preventiveAction: "Avoid walking in flooded areas",
      riskFactors: ["Monsoon risk", "Flooding", "Disease risk"], confidence: 0.96,
    },
    routing: { primaryDepartment: "BMC Drainage", escalationChain: ["Chief Engineer Drainage"] },
    verificationCount: 9, upvotes: 11, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_5",
    status: "IN_PROGRESS",
    location: { lat: 19.0596, lng: 72.8295, address: "Bandra West, Mumbai" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "SANITATION", subCategory: "Garbage Overflow", severity: 6, urgency: "MEDIUM",
      priority: "P3", citizenTitle: "Garbage overflow near Bandra station", slaHours: 48,
      citizenDescription: "Garbage bins overflowing near the station creating unhygienic conditions.",
      department: "Sanitation & Health Department", estimatedCostInr: 15000,
      publicSafetyThreat: false, preventiveAction: "Avoid the area if possible",
      riskFactors: ["Health hazard", "Mosquito breeding"], confidence: 0.93,
    },
    routing: { primaryDepartment: "BMC Sanitation", escalationChain: ["Chief Sanitary Inspector"] },
    verificationCount: 6, upvotes: 8, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_6",
    status: "CRITICAL",
    location: { lat: 19.0178, lng: 72.8478, address: "Dharavi, Mumbai" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "PUBLIC_SAFETY", subCategory: "Missing Manhole Cover", severity: 10, urgency: "CRITICAL",
      priority: "P1", citizenTitle: "Missing manhole cover in Dharavi", slaHours: 4,
      citizenDescription: "A manhole cover is missing on a busy road posing extreme danger to pedestrians and vehicles.",
      department: "Public Safety & Engineering Department", estimatedCostInr: 25000,
      publicSafetyThreat: true, preventiveAction: "Do not walk near the open manhole",
      riskFactors: ["Immediate danger", "Pedestrian risk", "Vehicle damage"], confidence: 0.99,
    },
    routing: { primaryDepartment: "BMC Engineering", escalationChain: ["Municipal Commissioner"] },
    verificationCount: 15, upvotes: 18, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 6 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },

  // BANGALORE
  {
    reporterId: "demo_user_7",
    status: "VERIFIED",
    location: { lat: 12.9716, lng: 77.5946, address: "MG Road, Bangalore" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "ROAD_DAMAGE", subCategory: "Road Cave-in", severity: 8, urgency: "HIGH",
      priority: "P2", citizenTitle: "Road cave-in on MG Road", slaHours: 24,
      citizenDescription: "A section of MG Road has caved in due to underground water pipe damage.",
      department: "BBMP Public Works", estimatedCostInr: 250000,
      publicSafetyThreat: true, preventiveAction: "Use alternate routes",
      riskFactors: ["Underground pipe damage", "High traffic", "Vehicle risk"], confidence: 0.95,
    },
    routing: { primaryDepartment: "BBMP", escalationChain: ["Chief Engineer BBMP"] },
    verificationCount: 11, upvotes: 14, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_8",
    status: "RESOLVED",
    location: { lat: 12.9352, lng: 77.6245, address: "Koramangala, Bangalore" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "GREEN_SPACES", subCategory: "Fallen Tree", severity: 4, urgency: "MEDIUM",
      priority: "P3", citizenTitle: "Fallen tree blocking road in Koramangala", slaHours: 48,
      citizenDescription: "A large tree has fallen blocking the main road after last night's storm.",
      department: "Horticulture Department", estimatedCostInr: 8000,
      publicSafetyThreat: false, preventiveAction: "Use alternate route",
      riskFactors: ["Road blockage", "Storm damage"], confidence: 0.92,
    },
    routing: { primaryDepartment: "BBMP Horticulture", escalationChain: ["Chief Horticulture Officer"] },
    verificationCount: 4, upvotes: 6, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_9",
    status: "IN_PROGRESS",
    location: { lat: 13.0358, lng: 77.5970, address: "Hebbal, Bangalore" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "WATER_INFRASTRUCTURE", subCategory: "Sewage Overflow", severity: 9, urgency: "CRITICAL",
      priority: "P1", citizenTitle: "Sewage overflow near Hebbal lake", slaHours: 4,
      citizenDescription: "Sewage is overflowing near Hebbal lake posing serious environmental and health risk.",
      department: "Jal Board / Water Supply Department", estimatedCostInr: 180000,
      publicSafetyThreat: true, preventiveAction: "Do not use lake water, avoid area",
      riskFactors: ["Environmental damage", "Health risk", "Lake pollution"], confidence: 0.98,
    },
    routing: { primaryDepartment: "BWSSB", escalationChain: ["Chief Engineer BWSSB", "Municipal Commissioner"] },
    verificationCount: 13, upvotes: 16, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },

  // CHENNAI
  {
    reporterId: "demo_user_10",
    status: "VERIFIED",
    location: { lat: 13.0827, lng: 80.2707, address: "Anna Nagar, Chennai" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "DRAINAGE", subCategory: "Waterlogging", severity: 7, urgency: "HIGH",
      priority: "P2", citizenTitle: "Severe waterlogging in Anna Nagar", slaHours: 24,
      citizenDescription: "Severe waterlogging on main road after heavy rains blocking traffic completely.",
      department: "Drainage & Sewerage Department", estimatedCostInr: 95000,
      publicSafetyThreat: true, preventiveAction: "Avoid driving through flooded roads",
      riskFactors: ["Flooding", "Monsoon", "Traffic disruption"], confidence: 0.96,
    },
    routing: { primaryDepartment: "GCC Drainage", escalationChain: ["Chief Engineer Drainage"] },
    verificationCount: 10, upvotes: 12, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_11",
    status: "RESOLVED",
    location: { lat: 13.0604, lng: 80.2496, address: "T Nagar, Chennai" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "ENCROACHMENT", subCategory: "Footpath Encroachment", severity: 3, urgency: "LOW",
      priority: "P4", citizenTitle: "Footpath encroachment in T Nagar", slaHours: 168,
      citizenDescription: "Shops have encroached on the footpath forcing pedestrians to walk on the road.",
      department: "Anti-Encroachment Cell", estimatedCostInr: 5000,
      publicSafetyThreat: false, preventiveAction: "Walk carefully on road",
      riskFactors: ["Pedestrian safety"], confidence: 0.88,
    },
    routing: { primaryDepartment: "GCC Anti-Encroachment", escalationChain: ["Zonal Deputy Commissioner"] },
    verificationCount: 3, upvotes: 4, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_12",
    status: "IN_PROGRESS",
    location: { lat: 13.1067, lng: 80.2941, address: "Perambur, Chennai" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "ELECTRICAL", subCategory: "Exposed Wires", severity: 9, urgency: "CRITICAL",
      priority: "P1", citizenTitle: "Exposed high voltage wires in Perambur", slaHours: 4,
      citizenDescription: "High voltage electrical wires are exposed and hanging low over a busy street.",
      department: "TANGEDCO Electricity Board", estimatedCostInr: 45000,
      publicSafetyThreat: true, preventiveAction: "Stay away from the wires, do not touch",
      riskFactors: ["Electrocution risk", "Fire hazard", "Immediate danger"], confidence: 0.99,
    },
    routing: { primaryDepartment: "TANGEDCO", escalationChain: ["Executive Engineer Electrical", "Municipal Commissioner"] },
    verificationCount: 14, upvotes: 17, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 12 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },

  // HYDERABAD
  {
    reporterId: "demo_user_13",
    status: "VERIFIED",
    location: { lat: 17.385, lng: 78.4867, address: "Hitech City, Hyderabad" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "ROAD_DAMAGE", subCategory: "Multiple Potholes", severity: 6, urgency: "MEDIUM",
      priority: "P3", citizenTitle: "Multiple potholes near Hitech City", slaHours: 72,
      citizenDescription: "Multiple potholes on the IT corridor road causing damage to vehicles.",
      department: "GHMC Public Works", estimatedCostInr: 75000,
      publicSafetyThreat: false, preventiveAction: "Drive slowly and carefully",
      riskFactors: ["Vehicle damage", "Traffic slowdown"], confidence: 0.93,
    },
    routing: { primaryDepartment: "GHMC", escalationChain: ["Chief Engineer GHMC"] },
    verificationCount: 7, upvotes: 9, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 4 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_14",
    status: "RESOLVED",
    location: { lat: 17.3616, lng: 78.4747, address: "Banjara Hills, Hyderabad" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "SANITATION", subCategory: "Open Garbage Dump", severity: 5, urgency: "MEDIUM",
      priority: "P3", citizenTitle: "Illegal garbage dump in Banjara Hills", slaHours: 48,
      citizenDescription: "An illegal garbage dump has formed near a residential area causing bad odour.",
      department: "GHMC Sanitation", estimatedCostInr: 20000,
      publicSafetyThreat: false, preventiveAction: "Keep windows closed",
      riskFactors: ["Health hazard", "Mosquito breeding", "Air pollution"], confidence: 0.90,
    },
    routing: { primaryDepartment: "GHMC Sanitation", escalationChain: ["Chief Sanitary Inspector"] },
    verificationCount: 5, upvotes: 6, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 8 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    reporterId: "demo_user_15",
    status: "IN_PROGRESS",
    location: { lat: 17.4399, lng: 78.4983, address: "Secunderabad, Hyderabad" },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    imageThumbUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/320px-Good_Food_Display_-_NCI_Visuals_Online.jpg",
    aiAnalysis: {
      category: "PUBLIC_SAFETY", subCategory: "Broken Footpath", severity: 5, urgency: "MEDIUM",
      priority: "P3", citizenTitle: "Broken footpath near Secunderabad station", slaHours: 72,
      citizenDescription: "Footpath tiles are broken and uplifted near the station causing trip hazard.",
      department: "GHMC Engineering", estimatedCostInr: 30000,
      publicSafetyThreat: false, preventiveAction: "Walk carefully on footpath",
      riskFactors: ["Trip hazard", "Elderly risk"], confidence: 0.89,
    },
    routing: { primaryDepartment: "GHMC Engineering", escalationChain: ["Executive Engineer GHMC"] },
    verificationCount: 4, upvotes: 5, verifications: [],
    createdAt: Timestamp.fromDate(new Date(Date.now() - 6 * 24 * 60 * 60 * 1000)),
    updatedAt: Timestamp.fromDate(new Date()),
  },
];

export async function seedDemoData() {
  console.log("Seeding demo data...");
  let count = 0;
  for (const report of SEED_REPORTS) {
    await addDoc(collection(db, "reports"), report);
    count++;
    console.log(`Seeded ${count}/${SEED_REPORTS.length}`);
  }
  console.log("✅ Seeding complete!");
  return count;
}
